### ISSUE TITLE
请问可以分享你的 zsh  Loading 的命令行动画吗？

### ISSUE THREAD

**Issue by seiuneko** [echohn/echohn.github.io#1]
在你的一篇博文中看到的
http://echohn.github.io/2016/10/01/about-improve-zsh-response-speed/
能不能分享下这个动画 谢谢～

**Comment by echohn** [comment]
将附件恢复原有后缀名。

node 安装 loading-cli。

启动脚本里执行以下命令即可。

```
cat 2.ans
node loading.js &
```

[2.ans.txt](https://github.com/echohn/echohn.github.io/files/874237/2.ans.txt)
[loading.js.txt](https://github.com/echohn/echohn.github.io/files/874238/loading.js.txt)
